#!/bin/bash
#

TL=/home/norbert/Development/TeX/texlive.git
NR=${1-10}

if [ $NR = "all" ] ; then
  NR=""
else
  NR="-$NR"
fi

DEST=./tlpdb

if [ ! -d $TL ] ; then
  echo "Not a directory $TL, exit." >&2
  exit 1
fi

mkdir -p $DEST
DEST=`realpath $DEST`

cd $TL

# the date format neets to be parseable as
#	DateTime
# in Neo4j (function datetime)
git log $NR --pretty=format:"%H %cd" --date=format:%FT%R%z Master/tlpkg/texlive.tlpdb | while read h d ; do
  echo "hash=$h,date=$d"
  if [ -d $DEST/$d ] ; then
    echo "$DEST/$d already present, skipping"
    continue
  fi
  mkdir -p $DEST/$d
  git checkout $h -- Master/tlpkg/texlive.tlpdb
  cp Master/tlpkg/texlive.tlpdb $DEST/$d/
done
