#!/bin/bash

todos=$(ls -d tlpdb/20* | tail -n +2)

for todo in $todos ; do
  i=$(echo $todo | cut -b 7-)
  echo "Working on $todo"
  ./tl-dump-neo4j --date="$i" --output=$todo/out $todo/texlive.tlpdb
  ./create-cypher-statements --path=$todo/out > $todo/cypher-import-statement
done



