#!/bin/bash

first="$1"
if [ ! -r "$first/texlive.tlpdb" ] ; then
  echo "Cannot read $first/texlive.tlpdb" >&2
  exit 1
fi
dtstr=$(echo $first | cut -b 7-)
rm -rf "$first/out"
./tl-dump-neo4j --initial --date="$dtstr" --output="$first/out" "$first/texlive.tlpdb"

cd "$first/out"

cmdline=
for x in node-*.csv ; do
  bn=`basename $x .csv`
  n=`echo $bn | sed -e 's/^node-//'`
  cmdline="$cmdline --nodes:$n $x"
done
for x in edge-*.csv ; do
  bn=`basename $x .csv`
  n=`echo $bn | sed -e 's/^edge-//'`
  cmdline="$cmdline --relationships:$n $x"
done

rm -rf ../graph.db
neo4j-import --into ../graph.db $cmdline


