#!/bin/bash

OVERWRITE=0
if [ "$1" = -f ] ; then
  OVERWRITE=1
fi

todos=$(ls -d tlpdb/20* | tail -n +2)

for todo in $todos ; do
  i=$(echo $todo | cut -b 7-)
  echo "Working on $todo"
  doit=1
  if [ -r $todo/out/node-TLPDB.csv -a -r $todo/cypher-import-statement ] ; then
    if [ $OVERWRITE = 1 ] ; then
      echo "Overwriting files in $todo/out"
    else
      echo "Skipping $todo, already converted."
      doit=0
    fi
  fi
  if [ $doit = 1 ] ; then
    ./tl-dump-neo4j --date="$i" --output=$todo/out $todo/texlive.tlpdb
    ./create-cypher-statements --path=$todo/out > $todo/cypher-import-statement
  fi
done



