#!/bin/bash

if [ -z "$NEO4J_USERNAME" ] ; then
  echo "need NEO4J_USERNAME environment variable, exiting!" >&2
  exit 1
fi
if [ -z "$NEO4J_PASSWORD" ] ; then
  echo "need NEO4J_PASSWORD environment variable, exiting!" >&2
  exit 1
fi
todos=$(ls -d tlpdb/20* | tail -n +2)
for todo in $todos ; do
  if [ ! -r $todo/cypher-import-statement ] ; then
    echo "not found: $todo/cypher-import-statement, exiting!" >&2
    exit 1
  fi
  echo "Running cypher statements $todo/cypher-import-statement"
  cat $todo/cypher-import-statement | cypher-shell
done



